#!/usr/bin/env python3
"""
Title: DCI - Direct Camera Interface
       Frame Grabber, Audio-Muxed Recorder, Auto-Transcriber, ANA Runner
       + Native Stereo-SBS Seam Detection (front-loaded)
Script Revision: v1.14.0
Date: June 14, 2026
Author: Craig C. Cline / seeitwith.org
AI co-author: Claude (Anthropic)
Patent: US Provisional #64/056,727

Revision Notes (v1.13.0 -> v1.14.0):
    AUDIO CUES: single beep on RECORD START, double beep on STOP & SAVE.
        beep() uses sounddevice for a real tone, falls back to the terminal
        bell, and never raises.
    SCO STUB: after ANA runs, DCI writes {stem}_sco_report.json holding the
        SCO inputs (transcript + ANA json + ANA report) with sco_findings=null.
        DCI calls NO AI. The frame-by-frame SCO is done by uploading the bundle
        to Claude online; Claude fills the findings and writes the completed
        report to Google Drive ("old stereo reports").
    CLEANUP: cleanup_diagnostics() removes *_anaglyph.mp4 / *_spacetime.png /
        *_orient.png after each capture. Bundle preserved:
        .mp4 / .wav / .srt / _ana_v1.48.json / _ana_v1.48_report.md / _sco_report.json

Revision Notes (v1.12.1 -> v1.13.0):
    ANA pointer updated from ana_v145.py -> ana_v148.py.
    All ANA version references (filenames, print strings, comments) bumped
    to v1.48. No pipeline logic changed — this is a pointer update only.
    The core SCO bundle is: .mp4 / .wav / .srt / _ana_v1.48.json / _ana_v1.48_report.md

Revision Notes (v1.12.0 -> v1.12.1):
    orient.png and anaglyph.mp4 removed from the SCO upload bundle summary.
    Both are diagnostic/visualization artifacts generated by ANA — useful for
    internal inspection but not required for SCO Protocol Card analysis in Claude.
    The core SCO bundle is: .mp4 / .wav / .srt / _ana_v1.48.json / _ana_v1.48_report.md

Revision Notes (v1.10.0 -> v1.12.0):
    USB DEVICE SELECTION added:
      - Audio: DCI enumerates input devices at startup and prefers one whose
        name matches AUDIO_DEVICE_HINT (default "USB"). Falls back to system
        default. Selected device is printed and used by the recorder thread.
        Hard-override with AUDIO_DEVICE_INDEX.
      - Camera: scan widened to indices 0-3. Hard-override with
        CAMERA_INDEX_OVERRIDE to pin a specific USB camera.
    ANA pointer updated to ana_v148.py (Questioner State + Room Reference).

Revision Notes (v1.9.0 -> v1.10.0):
    STEREO IS NOW FRONT-LOADED IN DCI.

    The seam-detection logic from ana_stereo.py is folded directly into this
    script (detect_stereo_seam). DCI now decides stereo-vs-monocular itself,
    BEFORE ANA runs, by locating the dark beam-splitter divider — not by
    aspect ratio. This eliminates the 1920x1080 "aspect ratio trap" that made
    ANA v1.48 misclassify standard-resolution SBS captures as monocular and
    silently drop the spatial signal.

    ana_stereo.py is no longer required by the pipeline. (ana_v148.py was
    already self-contained for the spatial signal — its compute_hdisp_spread
    and render_anaglyph both accept a seam_x argument. DCI now supplies it.)

    Off-center seams are PRESERVED, not snapped to frame center. Beam-splitter
    rigs rarely put the mirror edge at exactly W//2; DCI reports the true
    detected column and passes it forward verbatim.

    Two detection points:
      1. RECORD START  — fast live probe on the first frame. Advisory only:
                         prints "[STEREO PROBE] SBS seam x=NNN (offset)" so the
                         operator knows immediately whether the rig is framed.
      2. STOP & SAVE   — authoritative probe on the saved MP4 (multi-frame
                         average). Result drives how ANA is invoked.

    ANA invocation is capability-aware. DCI runs `ana_v148.py --help` once and
    checks whether ANA accepts --seam-x / --force-stereo:
      - If yes  -> DCI passes the detected seam and forces the spatial pass.
      - If no   -> DCI falls back to the legacy call (aspect-ratio gate) and
                   prints a clear note that ANA needs the matching CLI patch to
                   light up the spatial signal on standard-resolution SBS.
    Either way the pipeline never breaks.

    One press of 'S' still produces the complete SCO-ready bundle:
        {name}_{timestamp}.{mp4, wav, srt}                   (DCI)
        {name}_{timestamp}_ana_v1.48.{json, md}              (ANA)

Pipeline:
    DCI (this script) -> ANA v1.48 (physics) -> SCO (conversational, in Claude)

Dependencies:
    pip3 install opencv-python numpy sounddevice imageio-ffmpeg openai-whisper matplotlib

ANA file layout:
    Only ana_v148.py is needed. Keep it next to this DCI script (default), or
    set ANA_SCRIPT_PATH to its absolute path. ana_stereo.py is optional now and
    not used by this pipeline.
"""

# ----- CONFIGURATION -----
# ANA is auto-detected in the same folder as this script.
# Override by setting ANA_SCRIPT_PATH to an absolute path if you keep ANA elsewhere.
import os as _os
_DCI_DIR = _os.path.dirname(_os.path.abspath(__file__))
ANA_SCRIPT_PATH = _os.path.join(_DCI_DIR, "ana_v148.py")
ANA_TIMEOUT_S = 600  # stereo spatial pass; allow headroom

# ----- SCO STUB + CLEANUP -----
# DCI does NOT call any AI. It writes a local SCO stub holding the inputs
# (transcript + ANA physics) with sco_findings left null. The frame-by-frame
# SCO is done by uploading the bundle to Claude online; Claude fills in the
# findings and writes the completed report to Google Drive ("old stereo reports").
SCO_STUB_ENABLED = True

# ANA diagnostic artifacts removed after each capture (not part of the bundle).
SCO_CLEANUP_GLOBS = ["*_anaglyph.mp4", "*_spacetime.png", "*_orient.png"]

# ----- INPUT DEVICE SELECTION -----
AUDIO_DEVICE_HINT = "USB"      # prefer input device whose name contains this
AUDIO_DEVICE_INDEX = None      # set an int to hard-pin a sounddevice index
CAMERA_INDEX_OVERRIDE = None   # set an int (0-3) to hard-pin a camera
CAMERA_SCAN_RANGE = [0, 1, 2, 3]

# ----- STEREO SEAM DETECTION TUNING (folded from ana_stereo.py v1.41) -----
SEAM_SEARCH_FRAC = 0.18   # search +/- this fraction of width around center
SEAM_DARK_FRAC   = 0.55   # column mean < this * global mean => dark candidate
SEAM_PAD_PX      = 8      # extra px reported each side of the detected band
SEAM_PROBE_FRAMES = 25    # frames averaged for the authoritative (file) probe
# Confidence degrades with band narrowness / off-center distance:
SEAM_OFFSET_MED_FRAC = 0.05   # > 5% of width off center  -> MEDIUM
SEAM_OFFSET_LOW_FRAC = 0.10   # > 10% of width off center -> LOW

import cv2
import time
import os
import threading
import queue
import wave

try:
    import sounddevice as sd
    import numpy as np
    AUDIO_AVAILABLE = True
except (ImportError, OSError) as _audio_err:
    # ImportError: sounddevice not installed.
    # OSError: PortAudio library not found (installed but no backend).
    # Degrade gracefully to video-only instead of crashing on import.
    try:
        import numpy as np  # numpy may still be available/needed elsewhere
    except ImportError:
        pass
    AUDIO_AVAILABLE = False

try:
    import whisper
    WHISPER_AVAILABLE = True
except ImportError:
    WHISPER_AVAILABLE = False


# ===========================================================================
# STEREO SEAM DETECTION  (folded in from ana_stereo.py v1.41 detect_seam)
# ===========================================================================
def _seam_from_gray(gray, verbose=True):
    """
    Core seam locator. Operates on a single averaged grayscale image (H x W).
    Returns the seam dict. Off-center seams are preserved; we only fall back to
    frame center when NO dark central band is found at all.
    """
    H, W = gray.shape[:2]
    if W < 8:
        return {"is_stereo": False, "seam_x": W // 2, "center_offset_px": 0,
                "confidence": "NONE", "width": W, "height": H,
                "reason": "frame_too_small"}

    col_mean = gray.mean(axis=0)
    col_var  = gray.var(axis=0)
    global_mean = float(col_mean.mean())

    c0 = max(1, int(W * (0.5 - SEAM_SEARCH_FRAC)))
    c1 = min(W - 1, int(W * (0.5 + SEAM_SEARCH_FRAC)))

    dark_thr = SEAM_DARK_FRAC * global_mean
    var_thr  = float(np.percentile(col_var[c0:c1], 40))
    cand = [x for x in range(c0, c1)
            if col_mean[x] < dark_thr and col_var[x] <= var_thr]

    if not cand:
        # No dark divider found -> monocular. Do NOT invent a seam.
        return {"is_stereo": False, "seam_x": W // 2, "center_offset_px": 0,
                "confidence": "NONE", "width": W, "height": H,
                "reason": "no_dark_central_band"}

    # Longest contiguous run of dark columns = the divider band.
    runs, cur = [], [cand[0]]
    for x in cand[1:]:
        if x == cur[-1] + 1:
            cur.append(x)
        else:
            runs.append(cur); cur = [x]
    runs.append(cur)
    best = max(runs, key=len)
    band_lo, band_hi = best[0], best[-1]
    seam_center = (band_lo + band_hi) // 2
    band_width = band_hi - band_lo
    center_offset = seam_center - W // 2

    # Confidence: real divider bands are reasonably wide and near (but not
    # necessarily at) center. "A bit" off-center stays HIGH.
    abs_off = abs(center_offset)
    if band_width < 4 or abs_off > W * SEAM_OFFSET_LOW_FRAC:
        confidence = "LOW"
    elif band_width < 10 or abs_off > W * SEAM_OFFSET_MED_FRAC:
        confidence = "MEDIUM"
    else:
        confidence = "HIGH"

    seam = {
        "is_stereo": True,
        "seam_x": int(seam_center),
        "seam_x0": int(max(0, band_lo - SEAM_PAD_PX)),
        "seam_x1": int(min(W - 1, band_hi + SEAM_PAD_PX)),
        "band_width_px": int(band_width),
        "center_offset_px": int(center_offset),
        "confidence": confidence,
        "width": int(W), "height": int(H),
        "reason": "dark_divider_detected",
    }
    return seam


def detect_stereo_seam(source, verbose=True, probe_frames=SEAM_PROBE_FRAMES):
    """
    Detect a beam-splitter seam (dark vertical divider) and decide stereo SBS.

    Accepts either:
      - a BGR frame (np.ndarray)  -> fast single-frame probe (record-start use)
      - a video path (str)        -> authoritative multi-frame averaged probe

    Returns a seam dict (see _seam_from_gray). Key fields:
        is_stereo        : bool
        seam_x           : int   true divider column (may be off-center)
        center_offset_px : int   seam_x - W//2  (negative = left of center)
        confidence       : HIGH | MEDIUM | LOW | NONE
    """
    # ---- ndarray frame: single-frame probe ----
    if isinstance(source, np.ndarray):
        gray = cv2.cvtColor(source, cv2.COLOR_BGR2GRAY).astype(np.float32)
        seam = _seam_from_gray(gray, verbose=verbose)
        if verbose:
            _print_seam(seam, tag="PROBE/live")
        return seam

    # ---- path: average several frames for a stable read ----
    cap = cv2.VideoCapture(source)
    if not cap.isOpened():
        return {"is_stereo": False, "seam_x": 0, "center_offset_px": 0,
                "confidence": "NONE", "width": 0, "height": 0,
                "reason": "cannot_open_video"}
    total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT)) or 1
    idxs = np.linspace(0, max(0, total - 1),
                       min(total, probe_frames)).astype(int)
    grays = []
    for i in idxs:
        cap.set(cv2.CAP_PROP_POS_FRAMES, int(i))
        ok, f = cap.read()
        if ok:
            grays.append(cv2.cvtColor(f, cv2.COLOR_BGR2GRAY).astype(np.float32))
    cap.release()
    if not grays:
        return {"is_stereo": False, "seam_x": 0, "center_offset_px": 0,
                "confidence": "NONE", "width": 0, "height": 0,
                "reason": "no_frames_read"}
    gray = np.mean(grays, axis=0)
    seam = _seam_from_gray(gray, verbose=verbose)
    if verbose:
        _print_seam(seam, tag="STEREO/file")
    return seam


def _print_seam(seam, tag="STEREO"):
    """Operator-facing one-liner for a seam result."""
    if seam.get("is_stereo"):
        off = seam.get("center_offset_px", 0)
        off_txt = (f"offset {off:+d}px from center"
                   if off != 0 else "centered")
        print(f"[{tag}] SBS seam x={seam['seam_x']} ({off_txt}), "
              f"band {seam.get('band_width_px', '?')}px, "
              f"confidence {seam.get('confidence', '?')}")
    else:
        print(f"[{tag}] no central divider -> MONOCULAR "
              f"({seam.get('reason', 'n/a')})")


# ===========================================================================
# ANA CAPABILITY PROBE  (does this ANA accept --seam-x / --force-stereo?)
# ===========================================================================
_ANA_CAPS_CACHE = None

def ana_capabilities():
    """
    Run `ana_v148.py --help` once and cache which override flags it supports.
    Returns dict: {"seam_x": bool, "force_stereo": bool}
    A stock ANA v1.48 supports neither (it gates spatial on aspect ratio).
    """
    global _ANA_CAPS_CACHE
    if _ANA_CAPS_CACHE is not None:
        return _ANA_CAPS_CACHE
    caps = {"seam_x": False, "force_stereo": False}
    if not os.path.exists(ANA_SCRIPT_PATH):
        _ANA_CAPS_CACHE = caps
        return caps
    try:
        import subprocess, sys
        out = subprocess.run([sys.executable, ANA_SCRIPT_PATH, "--help"],
                             capture_output=True, text=True, timeout=30)
        helptext = (out.stdout or "") + (out.stderr or "")
        caps["seam_x"] = "--seam-x" in helptext
        caps["force_stereo"] = ("--force-stereo" in helptext
                                or "--stereo" in helptext)
    except Exception as e:
        print(f"[ANA] capability probe failed ({e}); assuming legacy CLI.")
    _ANA_CAPS_CACHE = caps
    return caps


# ===========================================================================
# AUDIO / MUX / TRANSCRIBE  (unchanged from v1.12.0)
# ===========================================================================
def find_active_sensor():
    """Find a working camera. CAMERA_INDEX_OVERRIDE pins a specific index;
    otherwise scan CAMERA_SCAN_RANGE and take the first that delivers frames."""
    indices = ([CAMERA_INDEX_OVERRIDE] if CAMERA_INDEX_OVERRIDE is not None
               else CAMERA_SCAN_RANGE)
    for index in indices:
        cap = cv2.VideoCapture(index)
        if cap.isOpened():
            ret, frame = cap.read()
            if ret:
                return cap, index
            cap.release()
        else:
            cap.release()
    return None, None


def select_audio_device():
    """
    Pick the audio input device.
    Priority: AUDIO_DEVICE_INDEX (hard pin) > name matching AUDIO_DEVICE_HINT
    (e.g. a USB mic) > system default. Returns (device_index_or_None, label).
    None means sounddevice uses the system default.
    """
    if not AUDIO_AVAILABLE:
        return None, "audio unavailable"
    try:
        devices = sd.query_devices()
    except Exception as e:
        print(f"[AUDIO] device query failed ({e}); using system default.")
        return None, "system default"

    if AUDIO_DEVICE_INDEX is not None:
        try:
            d = devices[AUDIO_DEVICE_INDEX]
            if d.get("max_input_channels", 0) > 0:
                return AUDIO_DEVICE_INDEX, f"pinned: {d['name']}"
            print(f"[AUDIO] pinned index {AUDIO_DEVICE_INDEX} has no inputs; "
                  f"falling back to hint/default.")
        except Exception:
            print(f"[AUDIO] pinned index {AUDIO_DEVICE_INDEX} invalid; "
                  f"falling back to hint/default.")

    hint = (AUDIO_DEVICE_HINT or "").lower()
    if hint:
        for i, d in enumerate(devices):
            if (d.get("max_input_channels", 0) > 0
                    and hint in d.get("name", "").lower()):
                return i, f"hint '{AUDIO_DEVICE_HINT}': {d['name']}"

    return None, "system default"

def audio_recorder_worker(filename, stop_event, shared_state, device=None):
    sample_rate = 44100
    channels = 1
    audio_queue = queue.Queue()

    def callback(indata, frames, time_info, status):
        audio_queue.put(indata.copy())

    try:
        with sd.InputStream(samplerate=sample_rate, channels=channels,
                            dtype='int16', callback=callback, device=device):
            with wave.open(filename, 'wb') as wf:
                wf.setnchannels(channels)
                wf.setsampwidth(2)
                wf.setframerate(sample_rate)
                while not stop_event.is_set() or not audio_queue.empty():
                    try:
                        data = audio_queue.get(block=False)
                        if not shared_state['paused']:
                            wf.writeframes(data.tobytes())
                    except queue.Empty:
                        time.sleep(0.01)
    except Exception as e:
        print(f"\n[AUDIO ERROR] {e}")

def merge_audio_video(video_path, audio_path, output_path):
    """Mux using imageio-ffmpeg bundled binary — no system ffmpeg required."""
    try:
        import imageio_ffmpeg
        import subprocess
        ffmpeg_exe = imageio_ffmpeg.get_ffmpeg_exe()
        cmd = [
            ffmpeg_exe, '-y',
            '-i', video_path,
            '-i', audio_path,
            '-c:v', 'copy',
            '-c:a', 'aac',
            '-shortest',
            output_path
        ]
        subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=True)
        return True
    except Exception as e:
        print(f"[MERGE ERROR] {e}")
        return False

def format_srt_timestamp(seconds):
    """Convert seconds to SRT timestamp: HH:MM:SS,mmm"""
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = int(seconds % 60)
    ms = int((seconds - int(seconds)) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"

def transcribe_to_srt(audio_path, srt_path, model_name='base'):
    """Run whisper on audio file, save SRT with timestamps."""
    if not WHISPER_AVAILABLE:
        print("[TRANSCRIBE SKIP] whisper not installed (pip3 install openai-whisper)")
        return False
    try:
        print(f"  Loading whisper model '{model_name}'...")
        model = whisper.load_model(model_name)
        print(f"  Transcribing {os.path.basename(audio_path)}...")
        result = model.transcribe(audio_path, verbose=False)

        with open(srt_path, 'w') as f:
            for i, seg in enumerate(result['segments'], 1):
                f.write(f"{i}\n")
                f.write(f"{format_srt_timestamp(seg['start'])} --> {format_srt_timestamp(seg['end'])}\n")
                f.write(f"{seg['text'].strip()}\n\n")
        return True
    except Exception as e:
        print(f"[TRANSCRIBE ERROR] {e}")
        return False


# ===========================================================================
# ANA RUNNER  (now stereo-aware)
# ===========================================================================
def run_ana(video_path, seam=None):
    """
    Invoke ANA v1.48 on the given video file. ANA writes its outputs into the
    video's folder.

    If `seam` indicates stereo AND this ANA build accepts seam/stereo overrides,
    DCI passes --seam-x <col> --force-stereo so the spatial signal runs even
    when aspect ratio < 2.5 (the standard-resolution SBS case). Otherwise DCI
    falls back to the legacy call and prints a note.
    """
    import subprocess
    import sys

    if not os.path.exists(ANA_SCRIPT_PATH):
        print(f"[ANA SKIP] ANA script not found at: {ANA_SCRIPT_PATH}")
        print(f"           Edit ANA_SCRIPT_PATH at the top of this file to point at your ana_v148.py")
        return False

    cmd = [sys.executable, ANA_SCRIPT_PATH, os.path.basename(video_path)]

    if seam and seam.get("is_stereo"):
        caps = ana_capabilities()
        if caps["seam_x"] and caps["force_stereo"]:
            cmd += ["--seam-x", str(seam["seam_x"]), "--force-stereo"]
            print(f"  Stereo SBS confirmed (seam x={seam['seam_x']}). "
                  f"Passing override to ANA -> spatial signal ENABLED.")
        else:
            print("  [ANA NOTE] Stereo SBS detected by DCI, but this ANA build")
            print("             does not accept --seam-x / --force-stereo.")
            print("             ANA will fall back to its aspect-ratio gate and")
            print("             will classify this 1920x1080 SBS as MONOCULAR,")
            print("             so the spatial (H-disparity) signal is lost.")
            print(f"             Detected seam x={seam['seam_x']} "
                  f"(offset {seam.get('center_offset_px', 0):+d}px).")
            print("             Patch ana_v148.py to accept these two flags to")
            print("             light up spatial on standard-resolution SBS.")

    try:
        print(f"  Running ANA v1.48 on {os.path.basename(video_path)}...")
        video_dir = os.path.dirname(os.path.abspath(video_path)) or "."
        result = subprocess.run(
            cmd,
            cwd=video_dir,
            capture_output=True,
            text=True,
            timeout=ANA_TIMEOUT_S
        )
        if result.stdout:
            for line in result.stdout.splitlines():
                if any(k in line for k in ("Questioner:", "Proximity:",
                        "Spacetime:", "CoV=", "spread=", "t=")):
                    print(f"   {line.strip()}")
        if result.returncode == 0:
            return True
        else:
            print(f"[ANA ERROR] Exit code {result.returncode}")
            if result.stderr:
                print(f"  stderr: {result.stderr[-500:]}")
            return False
    except subprocess.TimeoutExpired:
        print(f"[ANA ERROR] Timed out after {ANA_TIMEOUT_S} seconds.")
        return False
    except Exception as e:
        print(f"[ANA ERROR] {e}")
        return False


# ===========================================================================
# DASHBOARD
# ===========================================================================
def draw_unified_dashboard(frame, status_text, status_color, timestamp,
                           is_recording, display_filename, active_index,
                           stereo_tag="stereo: ?"):
    cv2.rectangle(frame, (0, 0), (frame.shape[1], 135), (0, 0, 0), -1)
    cv2.putText(frame, "[R] START/RESUME REC  |  [P] PAUSE REC  |  [S] STOP & SAVE",
                (20, 30), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (0, 255, 255), 2, cv2.LINE_AA)
    audio_tag = "AUDIO" if AUDIO_AVAILABLE else "audio-off"
    whisper_tag = "WHISPER" if WHISPER_AVAILABLE else "whisper-off"
    ana_tag = "ANA-1.48" if os.path.exists(ANA_SCRIPT_PATH) else "ana-off"
    cv2.putText(frame, f"[SPACE] SNAPSHOT  |  [Q] QUIT  |  {audio_tag}  {whisper_tag}  {ana_tag}  STEREO-AUTO",
                (20, 55), cv2.FONT_HERSHEY_SIMPLEX, 0.55, (255, 255, 255), 1, cv2.LINE_AA)
    cv2.putText(frame, f"{status_text}  |  Bus: {active_index}  |  {timestamp}",
                (20, 95), cv2.FONT_HERSHEY_SIMPLEX, 0.65, status_color, 2, cv2.LINE_AA)
    if is_recording:
        cv2.putText(frame, f"Cache: {display_filename}   |   {stereo_tag}",
                    (20, 120), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (180, 180, 180), 1, cv2.LINE_AA)


# ===========================================================================
# AUDIO CUES  (record start / stop)
# ===========================================================================
def beep(times=1, freq=880, dur_ms=120, gap_ms=90):
    """
    Short audible cue. Single beep = record start, double = stop & save.
    Real tone via sounddevice; falls back to the terminal bell.
    Never raises — an audio cue must never break the pipeline.
    """
    try:
        if AUDIO_AVAILABLE:
            fs = 44100
            t = np.linspace(0, dur_ms / 1000.0, int(fs * dur_ms / 1000.0), False)
            tone = (0.3 * np.sin(2 * np.pi * freq * t)).astype(np.float32)
            for i in range(times):
                sd.play(tone, fs, blocking=True)
                if i < times - 1:
                    time.sleep(gap_ms / 1000.0)
            return
    except Exception:
        pass
    for i in range(times):
        print("\a", end="", flush=True)
        if i < times - 1:
            time.sleep(gap_ms / 1000.0)


# ===========================================================================
# SCO STUB  +  DIAGNOSTIC CLEANUP
# ===========================================================================
def _read_text(path):
    """Read a text file if it exists; return '' on any failure."""
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as f:
            return f.read()
    except Exception:
        return ""


def write_sco_stub(video_basename):
    """
    Write {stem}_sco_report.json holding the SCO INPUTS only:
        capture metadata + transcript (srt) + ANA json + ANA report.
    sco_findings is null — Claude fills it during the online frame-by-frame
    pass and writes the completed report to Google Drive ("old stereo reports").
    Returns the stub path, or None. Never raises.
    """
    if not SCO_STUB_ENABLED:
        return None

    stem = os.path.splitext(video_basename)[0]
    srt        = f"{stem}.srt"
    ana_json   = f"{stem}_ana_v1.48.json"
    ana_report = f"{stem}_ana_v1.48_report.md"

    stub = {
        "capture": video_basename,
        "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "schema": "sco_report.v1",
        "pass_status": "stub",   # -> "complete" once Claude fills findings
        "inputs": {
            "transcript_srt": _read_text(srt) or None,
            "ana_json": _read_text(ana_json) or None,
            "ana_report_md": _read_text(ana_report) or None,
        },
        "sco_findings": None,    # filled online: snap / surprise / account + QI
        "drive_folder": "old stereo reports",
    }

    out_path = f"{stem}_sco_report.json"
    try:
        import json
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(stub, f, indent=2, ensure_ascii=False)
        print(f">> SCO stub saved: {out_path}  (findings filled online)")
        return out_path
    except Exception as e:
        print(f"[SCO STUB WARN] Could not write {out_path}: {e}")
        return None


def cleanup_diagnostics(folder="."):
    """
    Remove ANA diagnostic artifacts not part of the SCO bundle:
        *_anaglyph.mp4, *_spacetime.png, *_orient.png
    Keeps .mp4 / .wav / .srt / _ana_v1.48.json / _ana_v1.48_report.md / _sco_report.json.
    Never raises.
    """
    import glob
    removed = []
    for pattern in SCO_CLEANUP_GLOBS:
        for path in glob.glob(os.path.join(folder, pattern)):
            try:
                os.remove(path)
                removed.append(os.path.basename(path))
            except Exception as e:
                print(f"[CLEANUP WARN] Could not remove {path}: {e}")
    if removed:
        print(f">> Cleaned diagnostics: {', '.join(removed)}")
    return removed


# ===========================================================================
# MAIN PIPELINE
# ===========================================================================
def run_camera_pipeline():
    os.system('clear')

    frame_width = 1920
    frame_height = 1080
    encoder_fps = 30.0
    cache_video_filename = "sco_working_cache.mp4"
    cache_audio_filename = "sco_working_cache.wav"
    window_name = "Grounded Observer - Live Stream Monitor"

    print("=================================================================")
    print("DCI v1.14.0 — Direct Camera Interface")
    print("            record + transcribe + ANA v1.48 + stereo seam + SCO stub")
    print("=================================================================")
    if not AUDIO_AVAILABLE:
        print("[WARNING] Run: pip3 install sounddevice")
    if not WHISPER_AVAILABLE:
        print("[INFO] Whisper not installed. Auto-transcription disabled.")
        print("       pip3 install openai-whisper")
    ana_present = os.path.exists(ANA_SCRIPT_PATH)
    if not ana_present:
        print(f"[INFO] ANA v1.48 not found at: {ANA_SCRIPT_PATH}")
        print(f"       Edit ANA_SCRIPT_PATH at top of script to enable physics analysis.")
    else:
        print(f"[OK] ANA v1.48 detected at: {ANA_SCRIPT_PATH}")
        caps = ana_capabilities()
        if caps["seam_x"] and caps["force_stereo"]:
            print("[OK] ANA accepts --seam-x / --force-stereo "
                  "(spatial signal will run on standard-res SBS).")
        else:
            print("[WARN] ANA does NOT accept --seam-x / --force-stereo. "
                  "Standard-res SBS will be analyzed temporal-only until ANA is patched.")
    print("[OK] Native stereo seam detection active (ana_stereo.py not required).")
    audio_device, audio_label = select_audio_device()
    if AUDIO_AVAILABLE:
        print(f"[AUDIO] Input device: {audio_label}")
    print(f"Scanning for camera (indices {CAMERA_SCAN_RANGE if CAMERA_INDEX_OVERRIDE is None else [CAMERA_INDEX_OVERRIDE]})...")

    cap, active_index = find_active_sensor()
    if cap is None:
        print("[CRITICAL] No camera found. Check USB and macOS Privacy > Camera.")
        return

    cap.set(cv2.CAP_PROP_FRAME_WIDTH, frame_width)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, frame_height)
    actual_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    actual_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    video_writer = None
    audio_thread = None
    audio_stop_event = threading.Event()
    audio_shared_state = {'paused': False}
    is_recording = False
    is_paused = False
    frame_count = 0
    live_stereo_tag = "stereo: probing..."   # updated at record start

    print(f"Sensor locked: Index {active_index} at {actual_width}x{actual_height}")
    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)

    try:
        while True:
            ret, frame = cap.read()
            if not ret:
                print("[ERROR] Frame drop.")
                break

            frame_count += 1
            timestamp = time.strftime("%Y-%m-%d %H:%M:%S")

            if is_recording and not is_paused and video_writer is not None:
                video_writer.write(frame)

            display_frame = frame.copy()

            if not is_recording:
                status_text = "IDLE"
                status_color = (150, 150, 150)
            elif is_paused:
                status_text = "PAUSED"
                status_color = (0, 255, 255)
            else:
                indicator = " *" if (frame_count // 15) % 2 == 0 else ""
                status_text = f"RECORDING{indicator}"
                status_color = (0, 0, 255)

            draw_unified_dashboard(display_frame, status_text, status_color,
                                   timestamp, is_recording, "DUAL_TRACK_CACHE",
                                   active_index, live_stereo_tag)
            cv2.imshow(window_name, display_frame)
            key = cv2.waitKey(1) & 0xFF

            if key == ord('r') or key == ord('R'):
                if not is_recording:
                    fourcc = cv2.VideoWriter_fourcc(*'avc1')
                    video_writer = cv2.VideoWriter(cache_video_filename, fourcc, encoder_fps, (actual_width, actual_height))
                    if not video_writer.isOpened():
                        fourcc = cv2.VideoWriter_fourcc(*'mp4v')
                        video_writer = cv2.VideoWriter(cache_video_filename, fourcc, encoder_fps, (actual_width, actual_height))
                    if AUDIO_AVAILABLE:
                        audio_stop_event.clear()
                        audio_shared_state['paused'] = False
                        audio_thread = threading.Thread(
                            target=audio_recorder_worker,
                            args=(cache_audio_filename, audio_stop_event,
                                  audio_shared_state, audio_device))
                        audio_thread.start()
                    is_recording = True
                    is_paused = False
                    print(f"[{timestamp}] Recording started.")
                    beep(times=1)  # single beep = record start

                    # ---- FRONT-LOADED STEREO PROBE (live, advisory) ----
                    try:
                        live_seam = detect_stereo_seam(frame, verbose=True)
                        if live_seam.get("is_stereo"):
                            off = live_seam.get("center_offset_px", 0)
                            live_stereo_tag = (f"stereo: SBS x={live_seam['seam_x']} "
                                               f"({off:+d}px, {live_seam['confidence']})")
                        else:
                            live_stereo_tag = "stereo: MONOCULAR"
                    except Exception as e:
                        live_stereo_tag = "stereo: probe error"
                        print(f"[STEREO PROBE] error: {e}")
                elif is_paused:
                    is_paused = False
                    audio_shared_state['paused'] = False
                    print(f"[{timestamp}] Resumed.")

            elif key == ord('p') or key == ord('P'):
                if is_recording and not is_paused:
                    is_paused = True
                    audio_shared_state['paused'] = True
                    print(f"[{timestamp}] Paused.")

            elif key == ord('s') or key == ord('S'):
                if is_recording:
                    beep(times=2)  # double beep = stop & save
                    if video_writer:
                        video_writer.release()
                        video_writer = None
                    if AUDIO_AVAILABLE and audio_thread:
                        audio_stop_event.set()
                        audio_thread.join()
                        audio_thread = None
                    cv2.destroyAllWindows()
                    for _ in range(15):
                        cv2.waitKey(1)
                    os.system('clear')
                    print("=" * 50)
                    user_given_name = input("Filename (ENTER for default): ").strip() or "sco_sequence"
                    user_given_name = user_given_name.replace(" ", "_")
                    time_suffix = time.strftime("%Y%m%d_%H%M%S")
                    final_video_name = f"{user_given_name}_{time_suffix}.mp4"

                    if os.path.exists(cache_video_filename):
                        final_audio_name = f"{user_given_name}_{time_suffix}.wav"
                        final_srt_name = f"{user_given_name}_{time_suffix}.srt"

                        if AUDIO_AVAILABLE and os.path.exists(cache_audio_filename):
                            # Always preserve the WAV — signature analysis needs it
                            import shutil
                            shutil.copy(cache_audio_filename, final_audio_name)
                            print(f">> Audio saved: {final_audio_name}")

                            # Mux into MP4 (best effort - WAV stays regardless)
                            print("Merging audio + video (imageio-ffmpeg)...")
                            if merge_audio_video(cache_video_filename, cache_audio_filename, final_video_name):
                                print(f">> Video+audio merged: {final_video_name}")
                            else:
                                os.rename(cache_video_filename, final_video_name)
                                print(f">> Merge failed. Video saved silent: {final_video_name}")

                            # Auto-transcribe with whisper
                            if WHISPER_AVAILABLE:
                                print("Transcribing...")
                                if transcribe_to_srt(final_audio_name, final_srt_name):
                                    print(f">> Transcript saved: {final_srt_name}")
                                else:
                                    print(">> Transcription failed.")
                            else:
                                print(">> Skipping transcript (whisper not installed)")

                            # Clean up cache files
                            for f in [cache_video_filename, cache_audio_filename]:
                                try: os.remove(f)
                                except: pass
                        else:
                            os.rename(cache_video_filename, final_video_name)
                            print(f">> Video only: {final_video_name}")

                        # ---- AUTHORITATIVE STEREO DETECTION on saved MP4 ----
                        print()
                        print("Stereo seam detection (authoritative, multi-frame)...")
                        seam = detect_stereo_seam(final_video_name, verbose=True)

                        # ---- Auto-run ANA v1.48 (stereo-aware) ----
                        if os.path.exists(ANA_SCRIPT_PATH):
                            print()
                            print("Running ANA v1.48 physics analysis...")
                            if run_ana(final_video_name, seam=seam):
                                print(">> ANA v1.48 bundle saved (json + md)")
                            else:
                                print(">> ANA failed — check console output above")
                        else:
                            print(">> Skipping ANA (script not found)")

                        # ---- Write SCO stub (inputs only; findings filled online) ----
                        write_sco_stub(final_video_name)

                        # ---- Remove ANA diagnostic artifacts (keep the bundle) ----
                        cleanup_diagnostics(folder=".")

                        print()
                        print("=" * 60)
                        print(f"COMPLETE BUNDLE: {user_given_name}_{time_suffix}")
                        print("=" * 60)
                        print(f"  DCI media : .mp4 / .wav / .srt")
                        if seam.get("is_stereo"):
                            print(f"  STEREO SBS: seam x={seam['seam_x']} "
                                  f"(offset {seam.get('center_offset_px', 0):+d}px, "
                                  f"{seam.get('confidence', '?')} confidence)")
                        else:
                            print(f"  MONOCULAR : no central divider detected")
                        if os.path.exists(ANA_SCRIPT_PATH):
                            print(f"  ANA report: _ana_v1.48.json / _ana_v1.48_report.md")
                        print(f"  SCO stub  : _sco_report.json (findings filled online)")
                        print()
                        print("Upload the bundle to Claude online for frame-by-frame SCO.")
                        print("Claude fills the findings and saves the report to Drive")
                        print("(\"old stereo reports\").")

                    is_recording = False
                    is_paused = False
                    live_stereo_tag = "stereo: probing..."
                    print("Resuming live monitor...")
                    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)

            elif key == ord(' '):
                snap_time = time.strftime("%Y%m%d_%H%M%S")
                snap_filename = f"sco_frame_{snap_time}.png"
                cv2.imwrite(snap_filename, frame, [int(cv2.IMWRITE_PNG_COMPRESSION), 0])
                print(f"Snapshot: {snap_filename}")

            elif key == ord('q') or key == ord('Q'):
                break

    except KeyboardInterrupt:
        print("\nInterrupted.")
    finally:
        if video_writer: video_writer.release()
        if AUDIO_AVAILABLE and audio_thread:
            audio_stop_event.set()
            audio_thread.join()
        for f in [cache_video_filename, cache_audio_filename]:
            if os.path.exists(f):
                try: os.remove(f)
                except: pass
        cap.release()
        cv2.destroyAllWindows()
        for _ in range(5):
            cv2.waitKey(1)
        print("Pipeline closed.")


if __name__ == "__main__":
    run_camera_pipeline()
